# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/anaconda/lib/python2.7/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /opt/anaconda/lib/python2.7/site-packages/cmake/data/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/student/ClionProjects/cmpe250-project1-MehdiSaffar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/student/ClionProjects/cmpe250-project1-MehdiSaffar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/anaconda/lib/python2.7/site-packages/cmake/data/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/anaconda/lib/python2.7/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/ClionProjects/cmpe250-project1-MehdiSaffar/CMakeFiles /home/student/ClionProjects/cmpe250-project1-MehdiSaffar/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/ClionProjects/cmpe250-project1-MehdiSaffar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_survey_class

# Build rule for target.
test_survey_class: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_survey_class
.PHONY : test_survey_class

# fast build rule for target.
test_survey_class/fast:
	$(MAKE) -f CMakeFiles/test_survey_class.dir/build.make CMakeFiles/test_survey_class.dir/build
.PHONY : test_survey_class/fast

#=============================================================================
# Target rules for targets named test_linked_list

# Build rule for target.
test_linked_list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_linked_list
.PHONY : test_linked_list

# fast build rule for target.
test_linked_list/fast:
	$(MAKE) -f CMakeFiles/test_linked_list.dir/build.make CMakeFiles/test_linked_list.dir/build
.PHONY : test_linked_list/fast

#=============================================================================
# Target rules for targets named project1

# Build rule for target.
project1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project1
.PHONY : project1

# fast build rule for target.
project1/fast:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/build
.PHONY : project1/fast

LinkedList.o: LinkedList.cpp.o

.PHONY : LinkedList.o

# target to build an object file
LinkedList.cpp.o:
	$(MAKE) -f CMakeFiles/test_survey_class.dir/build.make CMakeFiles/test_survey_class.dir/LinkedList.cpp.o
	$(MAKE) -f CMakeFiles/test_linked_list.dir/build.make CMakeFiles/test_linked_list.dir/LinkedList.cpp.o
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/LinkedList.cpp.o
.PHONY : LinkedList.cpp.o

LinkedList.i: LinkedList.cpp.i

.PHONY : LinkedList.i

# target to preprocess a source file
LinkedList.cpp.i:
	$(MAKE) -f CMakeFiles/test_survey_class.dir/build.make CMakeFiles/test_survey_class.dir/LinkedList.cpp.i
	$(MAKE) -f CMakeFiles/test_linked_list.dir/build.make CMakeFiles/test_linked_list.dir/LinkedList.cpp.i
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/LinkedList.cpp.i
.PHONY : LinkedList.cpp.i

LinkedList.s: LinkedList.cpp.s

.PHONY : LinkedList.s

# target to generate assembly for a file
LinkedList.cpp.s:
	$(MAKE) -f CMakeFiles/test_survey_class.dir/build.make CMakeFiles/test_survey_class.dir/LinkedList.cpp.s
	$(MAKE) -f CMakeFiles/test_linked_list.dir/build.make CMakeFiles/test_linked_list.dir/LinkedList.cpp.s
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/LinkedList.cpp.s
.PHONY : LinkedList.cpp.s

LinkedList.test.o: LinkedList.test.cpp.o

.PHONY : LinkedList.test.o

# target to build an object file
LinkedList.test.cpp.o:
	$(MAKE) -f CMakeFiles/test_linked_list.dir/build.make CMakeFiles/test_linked_list.dir/LinkedList.test.cpp.o
.PHONY : LinkedList.test.cpp.o

LinkedList.test.i: LinkedList.test.cpp.i

.PHONY : LinkedList.test.i

# target to preprocess a source file
LinkedList.test.cpp.i:
	$(MAKE) -f CMakeFiles/test_linked_list.dir/build.make CMakeFiles/test_linked_list.dir/LinkedList.test.cpp.i
.PHONY : LinkedList.test.cpp.i

LinkedList.test.s: LinkedList.test.cpp.s

.PHONY : LinkedList.test.s

# target to generate assembly for a file
LinkedList.test.cpp.s:
	$(MAKE) -f CMakeFiles/test_linked_list.dir/build.make CMakeFiles/test_linked_list.dir/LinkedList.test.cpp.s
.PHONY : LinkedList.test.cpp.s

Node.o: Node.cpp.o

.PHONY : Node.o

# target to build an object file
Node.cpp.o:
	$(MAKE) -f CMakeFiles/test_survey_class.dir/build.make CMakeFiles/test_survey_class.dir/Node.cpp.o
	$(MAKE) -f CMakeFiles/test_linked_list.dir/build.make CMakeFiles/test_linked_list.dir/Node.cpp.o
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/Node.cpp.o
.PHONY : Node.cpp.o

Node.i: Node.cpp.i

.PHONY : Node.i

# target to preprocess a source file
Node.cpp.i:
	$(MAKE) -f CMakeFiles/test_survey_class.dir/build.make CMakeFiles/test_survey_class.dir/Node.cpp.i
	$(MAKE) -f CMakeFiles/test_linked_list.dir/build.make CMakeFiles/test_linked_list.dir/Node.cpp.i
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/Node.cpp.i
.PHONY : Node.cpp.i

Node.s: Node.cpp.s

.PHONY : Node.s

# target to generate assembly for a file
Node.cpp.s:
	$(MAKE) -f CMakeFiles/test_survey_class.dir/build.make CMakeFiles/test_survey_class.dir/Node.cpp.s
	$(MAKE) -f CMakeFiles/test_linked_list.dir/build.make CMakeFiles/test_linked_list.dir/Node.cpp.s
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/Node.cpp.s
.PHONY : Node.cpp.s

SurveyClass.o: SurveyClass.cpp.o

.PHONY : SurveyClass.o

# target to build an object file
SurveyClass.cpp.o:
	$(MAKE) -f CMakeFiles/test_survey_class.dir/build.make CMakeFiles/test_survey_class.dir/SurveyClass.cpp.o
	$(MAKE) -f CMakeFiles/test_linked_list.dir/build.make CMakeFiles/test_linked_list.dir/SurveyClass.cpp.o
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/SurveyClass.cpp.o
.PHONY : SurveyClass.cpp.o

SurveyClass.i: SurveyClass.cpp.i

.PHONY : SurveyClass.i

# target to preprocess a source file
SurveyClass.cpp.i:
	$(MAKE) -f CMakeFiles/test_survey_class.dir/build.make CMakeFiles/test_survey_class.dir/SurveyClass.cpp.i
	$(MAKE) -f CMakeFiles/test_linked_list.dir/build.make CMakeFiles/test_linked_list.dir/SurveyClass.cpp.i
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/SurveyClass.cpp.i
.PHONY : SurveyClass.cpp.i

SurveyClass.s: SurveyClass.cpp.s

.PHONY : SurveyClass.s

# target to generate assembly for a file
SurveyClass.cpp.s:
	$(MAKE) -f CMakeFiles/test_survey_class.dir/build.make CMakeFiles/test_survey_class.dir/SurveyClass.cpp.s
	$(MAKE) -f CMakeFiles/test_linked_list.dir/build.make CMakeFiles/test_linked_list.dir/SurveyClass.cpp.s
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/SurveyClass.cpp.s
.PHONY : SurveyClass.cpp.s

SurveyClass.test.o: SurveyClass.test.cpp.o

.PHONY : SurveyClass.test.o

# target to build an object file
SurveyClass.test.cpp.o:
	$(MAKE) -f CMakeFiles/test_survey_class.dir/build.make CMakeFiles/test_survey_class.dir/SurveyClass.test.cpp.o
.PHONY : SurveyClass.test.cpp.o

SurveyClass.test.i: SurveyClass.test.cpp.i

.PHONY : SurveyClass.test.i

# target to preprocess a source file
SurveyClass.test.cpp.i:
	$(MAKE) -f CMakeFiles/test_survey_class.dir/build.make CMakeFiles/test_survey_class.dir/SurveyClass.test.cpp.i
.PHONY : SurveyClass.test.cpp.i

SurveyClass.test.s: SurveyClass.test.cpp.s

.PHONY : SurveyClass.test.s

# target to generate assembly for a file
SurveyClass.test.cpp.s:
	$(MAKE) -f CMakeFiles/test_survey_class.dir/build.make CMakeFiles/test_survey_class.dir/SurveyClass.test.cpp.s
.PHONY : SurveyClass.test.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/project1.dir/build.make CMakeFiles/project1.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_survey_class"
	@echo "... test_linked_list"
	@echo "... project1"
	@echo "... LinkedList.o"
	@echo "... LinkedList.i"
	@echo "... LinkedList.s"
	@echo "... LinkedList.test.o"
	@echo "... LinkedList.test.i"
	@echo "... LinkedList.test.s"
	@echo "... Node.o"
	@echo "... Node.i"
	@echo "... Node.s"
	@echo "... SurveyClass.o"
	@echo "... SurveyClass.i"
	@echo "... SurveyClass.s"
	@echo "... SurveyClass.test.o"
	@echo "... SurveyClass.test.i"
	@echo "... SurveyClass.test.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

